nav:
  - Home: 'index.md'
  - Getting Started :
    - Customizing Bees : 'getting_started/bee_creation.md'
    - Language Files : 'getting_started/language_files.md'
  - Examples :
    - Examples : 'examples/examples.md'
    - Blaze Bee : 'examples/blaze.md'
  - Bee Data:
    - Custom Bee Data: 'bee_data/bee_data'
    - Biome Tags: 'bee_data/biome_tags'
    - Color Names: 'bee_data/color_names'
    - Bee Data Table: 'bee_data/data_table'
  -
  -
  - Versions: 
    - 1.16: https://wiki.resourcefulbees.com/en/1.16.3/
    - 1.15: https://wiki.resourcefulbees.com/en/1.15/


site_name: Resourceful Bees Docs
site_url: https://wiki.resourcefulbees.com/en/1.15/
docs_dir: docs

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition


theme:
  name: material
  icon:
    logo: material/beehive-outline
  palette:
    scheme: slate
    primary: red
    accent: pink

extra_css:
  - extra.css


site_description: |
  Welcome to the Resourceful Bees wiki!
  Here you will find information on how to customize your new bees.

extra:
  current_version: 1.16.3
  versions:
    1.16.3: 1.16.3
    1.15: 1.15
